/**
 * DO NOT EDIT THIS FILE DIRECTLY.
 * This file is generated following the conversion of 
 * @see [./src/constants.cjs]{@link ./src/constants.cjs}
 * 
 **/
export const LIMIT_FILES  = parseInt(process.env.CLONE_FILE_MAX_PATTERN) || 10000;


export const SKIP_MESSAGE = "skip-message";